name: SurfDock
channels:
  - pyg
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - pytorch=2.2
  - pytorch-cuda=12.1
  - torch-ema=0.3
  - torchmetrics=1.2
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - openmm=8.1
  - openmmforcefields=0.12
  - openff-toolkit=0.15
  - pdbfixer=1.9
  - openbabel=3.1
  - biopandas=0.4
  - plyfile=1.0
  - prody=2.4
  - spyrmsd
  - accelerate=0.15
  - biopython
  - huggingface_hub=0.17
  - mdanalysis=2.4
  - posebusters=0.2
  - tokenizers=0.13
  - transformers=4.29
  - rdkit=2023.03.1
  - e3nn
  - wandb
  - loguru
  - dimorphite-dl
  - mx::reduce
  - pip
  - pip:
      - fair-esm~=2.0.1
      - prefetch-generator
      - https://github.com/nuvolos-cloud/PyMesh/releases/download/v0.3.1/pymesh2-0.3.1-cp310-cp310-linux_x86_64.whl
